import { PreRegisteredGuest } from './types';

export const INITIAL_GUESTS_RAW: { nome: string; limite: number }[] = [
  { nome: 'Samylle Beltrão', limite: 1 },
  { nome: 'Vitoria Emilly', limite: 2 },
  { nome: 'Caroline Tâmega', limite: 1 },
  { nome: 'Thamires Félix', limite: 1 },
  { nome: 'Maria Letícia', limite: 1 },
  { nome: 'Vitória Francielle', limite: 0 },
  { nome: 'Maria Cecilia', limite: 0 },
  { nome: 'Anna Beatriz Melo', limite: 0 },
  { nome: 'Denya Fernanda', limite: 1 },
  { nome: 'Bárbara Santana', limite: 4 },
  { nome: 'Dayse Uchôa', limite: 1 },
  { nome: 'Giovanna Cabral', limite: 1 },
  { nome: 'Vera Lúcia', limite: 5 },
  { nome: 'Lucia Soares', limite: 0 },
  { nome: 'Joseane Soares', limite: 1 },
  { nome: 'Jordana Ranielle', limite: 1 },
  { nome: 'Josivania Pereira', limite: 1 },
  { nome: 'Genilsa Ferreira', limite: 0 },
  { nome: 'Simone Bernardo', limite: 0 },
  { nome: 'Andrea Demezio', limite: 1 },
  { nome: 'Esthefany Dmezio', limite: 1 },
  { nome: 'Graziela Borges', limite: 1 },
  { nome: 'Cris Cota', limite: 0 },
  { nome: 'Suegleide Florentino', limite: 3 },
  { nome: 'Olga Lima', limite: 1 },
  { nome: 'Paula Beiriz', limite: 0 },
  { nome: 'Fabíula Ribeiro', limite: 0 },
  { nome: 'Cicleide Brás', limite: 1 },
  { nome: 'Márcia Albuquerque', limite: 2 },
  { nome: 'Jamille Adrielly', limite: 1 },
  { nome: 'Rafaella Santos', limite: 1 },
  { nome: 'Karla Santana', limite: 1 },
  { nome: 'Vinicius', limite: 1 },
  { nome: 'Ana Paula', limite: 1 },
  { nome: 'Glaucia Buarque', limite: 1 },
  { nome: 'Joseane Freitas', limite: 1 },
  { nome: 'Janaina do Nascimento Silva', limite: 2 },
  { nome: 'Carlos Demóstenes da Silva', limite: 1 },
  { nome: 'José William Barbosa e Silva', limite: 2 },
  { nome: 'Diego Calisto Silva Santos', limite: 2 },
  { nome: 'Isadora Maria Siqueira de Abreu', limite: 1 },
  { nome: 'Gilvan Melo de Abreu', limite: 0 },
  { nome: 'Carolina Duarte de Abreu Madruga', limite: 1 },
  { nome: 'Vinicius Castro Lima', limite: 1 },
  { nome: 'Marcelo Andreatto Nogueira', limite: 2 },
  { nome: 'Milena Mirelle Lima da Silva', limite: 2 },
  { nome: 'Cinthya Élida Damasceno Burguez Santos', limite: 0 },
  { nome: 'Arthur Plácido de Oliveira', limite: 0 },
  { nome: 'Juan Gabriel Rocha de Oliveira', limite: 1 },
  { nome: 'Joel Helder da Silva Morais', limite: 1 },
  { nome: 'Wilder de Sá Santos', limite: 1 },
  { nome: 'Wendel de Sá Santos', limite: 1 },
  { nome: 'Kayke Yuri Costa Magalhães', limite: 0 },
  { nome: 'Kennedy Morais da Veiga Costa', limite: 0 },
  { nome: 'Alexandre César Araújo', limite: 2 },
  { nome: 'Thiago André Gomes Antunes', limite: 1 },
  { nome: 'Roselândia Alcides Gaspar', limite: 1 },
  { nome: 'Alexandra Feitosa d\'Almeida', limite: 1 },
];

export function generateInitialGuestList(): PreRegisteredGuest[] {
  return INITIAL_GUESTS_RAW.map((g, index) => ({
    id: `guest-${index + 1}`,
    nome: g.nome,
    limite_acompanhantes: g.limite,
    status: 'pendente',
    telefone: '',
    acompanhantes_nomes: [],
    total_confirmados: 0,
    palpite: undefined,
    mensagem: '',
    confirmado_em: undefined,
  }));
}
